[kodama]
trees = "./" 
assets = "assets"
base-url = "/"
themes = [
  "themes/default.html",
  "themes/serena.html",
  "themes/kodama.html",
]

[toc]
placement = "right"
sticky = true
mobile-sticky = true
max-width = "max-content"

[build]
typst-root = "./"
short-slug = true
pretty-urls = true
footer-mode = "embed"
inline-css = true
asref = false
output = "./publish"

[serve]
edit = "vscode://file/"
output = "./.cache/publish"
command = ["miniserve", "<output>", "--index", "index.html", "--pretty-urls", "--port", "8080"]
